services:
  shyntr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shyntr_app
    ports:
      - "7496:7496" # Public Port (SHYN)
      - "7497:7497" # Admin Port (ADMN)
    environment:
      - DSN=postgres://shyntr:secretpassword@postgres:5432/shyntr?sslmode=disable
      - APP_SECRET=12345678901234567890123456789012
      - PORT=7496
      - ADMIN_PORT=7497
      - ISSUER_URL=http://localhost:7496
      - EXTERNAL_LOGIN_URL=http://localhost:3000/login
      - EXTERNAL_CONSENT_URL=http://localhost:3000/consent

      # Security
      - ADMIN_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - LOG_LEVEL=info
      - SKIP_TLS_VERIFY=true #Development only
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shyntr-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7496/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    command: >
      sh -c "./shyntr migrate && ./shyntr serve"

  shyntr-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shyntr_app_client_create
    environment:
      - DSN=postgres://shyntr:secretpassword@postgres:5432/shyntr?sslmode=disable
      - APP_SECRET=12345678901234567890123456789012
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shyntr-net
    command: >
      sh -c "./shyntr create-client default test-client secret"

  postgres:
    image: postgres:16-alpine
    container_name: shyntr_db
    environment:
      - POSTGRES_USER=shyntr
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=shyntr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shyntr"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shyntr-net

volumes:
  postgres_data:

networks:
  shyntr-net:
    driver: bridge
