// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/management/clients": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a new OAuth2/OIDC client under the specified tenant enforcing OAuth 2.1 standards.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2 Clients"
                ],
                "summary": "Create OIDC Client",
                "parameters": [
                    {
                        "description": "Client Configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOAuth2ClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOAuth2ClientRequest"
                        }
                    }
                }
            }
        },
        "/admin/management/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves global or tenant-specific usage statistics and active connection counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID (for filtering)",
                        "name": "tenant_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/management/saml-clients": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a legacy SAML Service Provider in the system for federation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SAML Clients"
                ],
                "summary": "Create SAML Client",
                "parameters": [
                    {
                        "description": "SAML Client Configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSAMLClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSAMLClientRequest"
                        }
                    }
                }
            }
        },
        "/admin/management/tenants": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists all tenants configured within the identity hub.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "List Tenants",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TenantResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new isolated tenant environment with strict data boundaries.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "Create Tenant",
                "parameters": [
                    {
                        "description": "Tenant Information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.Tenant"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateOAuth2ClientRequest": {
            "type": "object",
            "required": [
                "grant_types",
                "name",
                "redirect_uris",
                "tenant_id"
            ],
            "properties": {
                "allowed_cors_origins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://app.example.com"
                    ]
                },
                "audience": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "api-service"
                    ]
                },
                "backchannel_logout_uri": {
                    "type": "string",
                    "example": "https://api.example.com/backchannel-logout"
                },
                "client_id": {
                    "type": "string",
                    "example": "my-web-app"
                },
                "client_secret": {
                    "type": "string",
                    "example": "super-secure-secret-key"
                },
                "enforce_pkce": {
                    "type": "boolean",
                    "example": true
                },
                "grant_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "authorization_code",
                        "refresh_token"
                    ]
                },
                "jwks": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "My Frontend Application"
                },
                "post_logout_redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://app.example.com/logout"
                    ]
                },
                "public": {
                    "type": "boolean",
                    "example": false
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://app.example.com/callback"
                    ]
                },
                "response_modes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "query",
                        "form_post"
                    ]
                },
                "response_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "code"
                    ]
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "openid",
                        "profile",
                        "email",
                        "offline_access"
                    ]
                },
                "subject_type": {
                    "type": "string",
                    "example": "public"
                },
                "tenant_id": {
                    "type": "string",
                    "example": "default"
                },
                "token_endpoint_auth_method": {
                    "type": "string",
                    "example": "client_secret_basic"
                }
            }
        },
        "dto.CreateSAMLClientRequest": {
            "type": "object",
            "properties": {
                "acs_url": {
                    "type": "string"
                },
                "allowed_scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "attribute_mapping": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/entity.AttributeMappingRule"
                    }
                },
                "encrypt_assertion": {
                    "type": "boolean"
                },
                "entity_id": {
                    "type": "string"
                },
                "force_authn": {
                    "type": "boolean"
                },
                "metadata_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sign_assertion": {
                    "type": "boolean"
                },
                "sign_response": {
                    "type": "boolean"
                },
                "slo_url": {
                    "type": "string"
                },
                "sp_certificate": {
                    "type": "string"
                },
                "sp_encryption_certificate": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateTenantRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.TenantResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issuer_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.AttributeMappingRule": {
            "type": "object",
            "properties": {
                "fallback": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "target_scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "entity.Tenant": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issuer_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Shyntr Identity Hub API",
	Description:      "Protocol Agnostic Zero Trust Identity Broker",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
